Django/djangoproject.com-master/djangoproject.com-master/blog/urls.py
from django.urls import path

from . import views

app_name = 'weblog'
urlpatterns = [
    path(
        '<int:year>/<str:month>/<int:day>/<slug>/',
        views.BlogDateDetailView.as_view(),
        name="entry"
    ),
    path(
        '<int:year>/<str:month>/<int:day>/',
        views.BlogDayArchiveView.as_view(),
        name="archive-day"
    ),
    path(
        '<int:year>/<str:month>/',
        views.BlogMonthArchiveView.as_view(),
        name="archive-month"
    ),
    path(
        '<int:year>/',
        views.BlogYearArchiveView.as_view(),
        name="archive-year"
    ),
    path(
        '',
        views.BlogArchiveIndexView.as_view(),
        name="index"
    ),
]

Django/djangoproject.com-master/djangoproject.com-master/contact/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import ContactFoundation

urlpatterns = [
    path('foundation/', ContactFoundation.as_view(), name='contact_foundation'),
    path('sent/', TemplateView.as_view(template_name='contact/sent.html'), name='contact_form_sent'),
]

Django/djangoproject.com-master/djangoproject.com-master/contact/forms.py
import logging

import django
from contact_form.forms import ContactForm
from django import forms
from django.conf import settings
from django.contrib.sites.models import Site
from django.utils.encoding import force_bytes
from pykismet3 import Akismet, AkismetServerError

logger = logging.getLogger(__name__)


class BaseContactForm(ContactForm):
    message_subject = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'required', 'placeholder': 'Message subject'}),
        label='Message subject',
    )
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'required', 'placeholder': 'E-mail'}))
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'required', 'placeholder': 'Name'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'required', 'placeholder': 'Your message'}))

    def subject(self):
        # Strip all linebreaks from the subject string.
        subject = ''.join(self.cleaned_data["message_subject"].splitlines())
        return "[Contact form] " + subject

    def message(self):
        return "From: {name} <{email}>\n\n{body}".format(**self.cleaned_data)

    def clean_body(self):
        """
        Check spam against Akismet.

        Backported from django-contact-form pre-1.0; 1.0 dropped built-in
        Akismet support.
        """
        if 'body' in self.cleaned_data and getattr(settings, 'AKISMET_API_KEY', None):
            try:
                akismet_api = Akismet(
                    api_key=settings.AKISMET_API_KEY,
                    blog_url='http://%s/' % Site.objects.get_current().domain,
                    user_agent='Django {}.{}.{}'.format(*django.VERSION)
                )

                akismet_data = {
                    'user_ip': self.request.META.get('REMOTE_ADDR', ''),
                    'user_agent': self.request.META.get('HTTP_USER_AGENT', ''),
                    'referrer': self.request.META.get('HTTP_REFERER', ''),
                    'comment_content': force_bytes(self.cleaned_data['body']),
                    'comment_author': self.cleaned_data.get('name', ''),
                }
                if getattr(settings, 'AKISMET_TESTING', None):
                    # Adding test argument to the request in order to tell akismet that
                    # they should ignore the request so that test runs affect the heuristics
                    akismet_data['test'] = 1
                if akismet_api.check(akismet_data):
                    raise forms.ValidationError("Akismet thinks this message is spam")
            except AkismetServerError:
                logger.error('Akismet server error')
        return self.cleaned_data['body']


class FoundationContactForm(BaseContactForm):
    recipient_list = ["dsf-board@googlegroups.com"]

Django/djangoproject.com-master/djangoproject.com-master/contact/views.py
from contact_form.views import ContactFormView
from django.urls import reverse

from .forms import FoundationContactForm


class ContactFoundation(ContactFormView):
    form_class = FoundationContactForm
    template_name = 'contact/foundation.html'

    def get_success_url(self):
        return reverse('contact_form_sent')

Django/djangoproject.com-master/djangoproject.com-master/djangoproject/templates/contact/coc.html
{% extends "base_3col.html" %}

{% block title %}Django Code of Conduct Feedback{% endblock %}

{% block content %}
<h1>Django Code of Conduct Feedback</h1>
{% include "contact/coc_form.html" %}
{% endblock %}

Django/djangoproject.com-master/djangoproject.com-master/djangoproject/templates/contact/coc_form.html
<form action="{% url "contact_coc" %}" method="post" accept-charset="utf-8" class="wide">
{% csrf_token %}

{# hardcoding inputs because they'll be included on the CoC page itself #}
  <p>
    <label for="id_name">Your name (optional):</label>
    {% if form.name.errors %}<p class="errors">{{ form.name.errors.as_text }}</p>{% endif %}
    <input id="id_name" class="required" type="text" name="name">
  </p>
  <p>
    <label for="id_email">Your email address (optional):</label>
    {% if form.email.errors %}<p class="errors">{{ form.email.errors.as_text }}</p>{% endif %}
    <input id="id_email" class="required" type="text" name="email">
  </p>
  <p>
    <label for="id_body">Your message:</label>
    {% if form.body.errors %}<p class="errors">{{ form.body.errors.as_text }}</p>{% endif %}
    <textarea id="id_body" class="required" rows="10" name="body" cols="40"></textarea>
  </p>
  <p class="submit"><input type="submit" value="Send &rarr;"></p>

</form>

Django/djangoproject.com-master/djangoproject.com-master/djangoproject/templates/contact/foundation.html
{% extends "base_foundation.html" %}

{% block title %}Contact the Django Software Foundation{% endblock %}

{% block content %}
<h1>Contact the Django Software Foundation</h1>
<p>This contact form is for the Django Software Foundation - the legal and
  fundraising arm of the Django project.</p>
<p>If you want to report a bug, feature request, or documentation issue in Django,
  use the <a href="https://code.djangoproject.com">ticket tracker</a>.</p>
<p>If you want to report a problem with this website, use the
  <a href="https://github.com/django/djangoproject.com">Github repo</a>.</p>
<p>If you've got questions about how to use Django, use the
  <a href="https://groups.google.com/forum/#!forum/django-users">django-users mailing list</a>.</p>
<form action="." method="post" accept-charset="utf-8" class="form-input">
{% csrf_token %}
  <p>
    {% if form.name.errors %}<p class="errors">{{ form.name.errors.as_text }}</p>{% endif %}
    {{ form.name }}
  </p>
  <p class="form-email">
    {% if form.email.errors %}<p class="errors">{{ form.email.errors.as_text }}</p>{% endif %}
    {{ form.email }}
  </p>
  <p>
    {% if form.message_subject.errors %}<p class="errors">{{ form.message_subject.errors.as_text }}</p>{% endif %}
    {{ form.message_subject }}
  </p>
  <p>
    {% if form.body.errors %}<p class="errors">{{ form.body.errors.as_text }}</p>{% endif %}
    {{ form.body }}
  </p>
  <p class="submit"><input type="submit" class="cta" value="Send &rarr;"></p>
</form>
{% endblock %}

Django/djangoproject.com-master/djangoproject.com-master/djangoproject/templates/contact/sent.html
{% extends "base_foundation.html" %}

{% block title %}Message sent{% endblock %}

{% block content %}
  <h1>Message sent</h1>
  <h2 class="deck">Your message has been sent; thanks!</h2>
  <p>
    Your mail <em>will</em> be read by a real, live human being. We can't
    guarantee when or whether you'll get a reply, but your message
    <em>will</em> be read, generally within the next couple of days.
  </p>
  <p>
    If you're expecting a reply and don't get one, please feel free
    to send a reminder. Please wait a few days, however, unless
    it's an emergency.
  </p>
{% endblock %}